include:
  - project: registry/gitlab-ci
    file:
    - gradle.yml
    - variables.yml


variables:
  extends: .variables
  JAVA_VERSION: "17_jdk"
  GRADLE_VERSION: "8.3" # Версия Gradle
  ARTIFACT_PATH: "build/bin/native/releaseExecutable/*ihub-runner-spy*"
      
stages:          # List of stages for jobs, and their order of execution
  - build
#   - test
#   - deploy

build-job:       # This job runs in the build stage, which runs first.
  extends:
    - .gradle
  stage: build
  script:
    - echo proxy=http://proxy.sberdevices.ru:31282 >> /etc/yum.conf
    - gradle build 
